export const dishes = [
    {
       name: 'Lasagna Bolognese',
       img: 'https://images.unsplash.com/photo-1586197132548-e2e19edf9f89?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
       description: 'Lasagna Bolognese is a typical Sunday lunch or main course meal, and adults and children appreciate it for its rich and tasty flavor.',
       price: 13,
       availablity: true,
       ingredients: 'It’s made with fresh layers of lasagne sheets, bechamel sauce, bolognese sauce, and plenty of parmesan cheese.',
    },{
        name: 'Veal Milanese',
        img: 'https://www.nonnabox.com/wp-content/uploads/Authentic_Veal_Milanese.jpg',
        description: 'Veal Milanese is one of the most famous Italian dishes, with origins in Milan. This traditional recipe calls for a thick veal cut, but modern variations use a thin, boneless veal cut.',
        price: 15,
        availablity: true,
        ingredients: 'It is made with breadcrumbs, spices, and herbs and fried in butter to give the veal Milanese an unmistakable flavor.',
     },{
        name: 'Gnocchi Sorrento',
        img: 'https://images.pexels.com/photos/6659612/pexels-photo-6659612.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description: 'Gnocchi Alla Sorrentina is a great comfort food dish made with soft potato gnocchi, baked in a creamy tomato sauce and mozzarella cheese.',
        price: 12,
        availablity: false,
        ingredients: 'The soft gnocchi is lightly baked, and the bubbling creamy cheese and mozzarella are hard to beat.', 
     },{
        name: 'Spaghetti Carbonara',
        img: 'https://images.unsplash.com/photo-1588013273468-315fd88ea34c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1738&q=80',
        description: 'Carbonara is another classic Italian pasta dish made with simple ingredients and bursting with flavor. ',
        price: 14,
        availablity: true,
        ingredients: 'It is made with egg, cured pork, hard cheese, and black pepper. The cheese is usually Pecorino Romano or Parmigiano-Reggiano.',
     },{
        name: 'Antipasto Italiano',
        img: 'https://images.pexels.com/photos/5639423/pexels-photo-5639423.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description: 'Antipasto means “before the meal” and is a combination of small bites of tasty food – usually combined with wine or beer to stimulate your appetite before the main meal.',
        price: 10,
        availablity: false,
        ingredients: 'Typical ingredients include cured meats, olives, mushrooms, pepperoncini, anchovies, various cheeses, and artichoke hearts.', 
     },{
        name: 'Cavatelli',
        img: 'https://images.unsplash.com/photo-1523218475566-ea0db0c23067?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80',
        description: 'Cavatelli is small pasta shells from eggless semolina dough commonly cooked with garlic and broccoli.',
        price: 7,
        availablity: true,
        ingredients: 'Variants add cheese to the dough mix. It’s simple but made the right way, intensely flavorful.',
     },{
        name: 'Fettuccini Alfredo',
        img: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2132&q=80',
        description: 'Fettuccine Alfredo is a fresh pasta dish made with fettuccine, butter, and Parmesan cheese.',
        price: 18,
        availablity: false,
        ingredients: 'As the cheese melts, it forms a smooth and creamy sauce coating the pasta. You can use Alfredo to coat broccoli and partner with crispy chicken.', 
     },{
        name: 'Pork Braciola',
        img: 'https://images.pexels.com/photos/1307658/pexels-photo-1307658.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description: 'Known in Italy as Involtini, Braciola is a meat chop or cutlet wrapped or rolled around a stuffing.',
        price: 15,
        availablity: true,
        ingredients: 'Often browned, then baked or braised in wine or stock, you can fill them with anything. It is combined with bread crumbs and parmesan cheese and finished in a tomato sauce.',
     },{
        name: 'Pizza Margherita',
        img: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1738&q=80',
        description: 'To get a full authentic Italian experience, you have to go with the Margherita.',
        price: 9,
        availablity: true,
        ingredients: 'Simple, fresh, and flavorful, Pizza Margherita is made with tomatoes, mozzarella, fresh basil, and olive oil and baked at high temperatures for a crispy-on-the-outside crust.',
     },
];